### PR TITLE
refactor(api): redo endpoints

### PR DESCRIPTION
**Pull request by devnote-dev**
- Change a lot of the endpoint methods to what they should reflect
- General code and formatting cleanup

**This is a breaking change** but it is a necessary one which people should get used to before the next major version of Dashactyl releases which will likely have these endpoint changes.

### CODE REVIEW

**Review by real2two — COMMENTED** [review]
I don't really care too much about Dashactyl 0.x anymore, since I'm working on 1.0, but this update seems pretty nice, but I'll need to have an updated Dashactyl API documentation to match this. 

Also, I'd recommend changing any `res.send({json:"object"});` to `res.json({json:"object"});`, since it's more organized.

I'll push this soon, after I make an updated API documentations matching this, or if someone else does. (but I'm busy with other projects, so I might not be able to do that.)

**Review by devnote-dev — COMMENTED** [review]
JSON responses sorted now and paired an endpoint. PR should be ready to merge code-wise, documentation can be PRed too.

**Review by real2two — APPROVED** [review]

**Comment by real2two** [comment]
Tell me when I should merge it.

**Review by real2two — APPROVED** [review]
Looks pretty good. (damn you worked hard on this, thanks!)

**Pull request closed without merging**
